inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent

Naming/InclusiveLanguage:
  Enabled: false
